# Site settings
title: LC - Lucy Cosmetics
description: "Dovoľte, aby sme Vás privítali v našom salóne krásy KARLOTT v Pezinku na Kollárovej 11. Zastavte sa na chvíľu a doprajte trochu komfortu Vašej pleti i vlasom, so zachovaním mladistvého vzhľadu a módnych trendov. Náš profesionálny tím Vám bude pri tom všetkom nápomocný. Doprajte si u nás relax a uvoľnenie, a hlavne vylepšite si svoje sebavedomie. Vaša spokojnosť bude našim úspechom. Nájdete u nás širokú škálu služieb v oblasti kaderníctva, vizáže a líčenia, klasickej i prístrojovej kozmetiky."
url: "https://lucy-cosmetics.github.io"
author:
  name: "Ivanka a Andrej Hranickí"
  email: "ado.hranicky@gmail.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

gems: 
    - jekyll-sitemap
